server:
  port: 7777
oss:
  accessKey: KtYLGjx0Ib_yE6qRwwtVS7EtllU1wBvgRQUxBbSF
  secretKey: N3ZhyfIjQFE1zETfeF4ZBMmx3edMDBZRl5_lB7dF
  bucket: diaoyang-blog
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dy_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

  redis:
#    家的ip注意修改
    host: 192.168.86.129
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
mybatis-plus:
  configuration:
    # 日志

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis操作数据库日志
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
